// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VincitWebApplication.Persistence.Contexts;

namespace VincitWebApplication.Migrations
{
    [DbContext(typeof(iot_dbContext))]
    partial class iot_dbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("VincitWebApplication.Domain.Models.CubesensorsDatum", b =>
                {
                    b.Property<long?>("Battery")
                        .HasColumnType("INT(10,0)");

                    b.Property<long?>("Cable")
                        .HasColumnType("INT(10,0)");

                    b.Property<long?>("Humidity")
                        .HasColumnType("INT(10,0)");

                    b.Property<long?>("Light")
                        .HasColumnType("INT(10,0)");

                    b.Property<byte[]>("MeasurementTime")
                        .IsRequired()
                        .HasColumnType("DATETIME2(7)");

                    b.Property<long?>("Noise")
                        .HasColumnType("INT(10,0)");

                    b.Property<long?>("Pressure")
                        .HasColumnType("INT(10,0)");

                    b.Property<long?>("Rssi")
                        .HasColumnType("INT(10,0)");

                    b.Property<string>("SensorId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<long?>("Temperature")
                        .HasColumnType("INT(10,0)");

                    b.Property<long?>("Voc")
                        .HasColumnType("INT(10,0)");

                    b.Property<long?>("VocResistance")
                        .HasColumnType("INT(10,0)");

                    b.ToTable("cubesensors_data");
                });

            modelBuilder.Entity("VincitWebApplication.Domain.Models.OutsideTemperature", b =>
                {
                    b.Property<byte[]>("MeasurementTime")
                        .HasColumnType("DATETIME2");

                    b.Property<byte[]>("Temperature")
                        .HasColumnType("NUMERIC");

                    b.ToTable("outside_temperature");
                });
#pragma warning restore 612, 618
        }
    }
}
